#!/bin/sh
### STILL NEEDS TO BE CHANGED ###

echo Making all messages for AIRT...
# repeat this for each .po file in /po:
xgettext --language=PHP --join-existing --no-location --output=en.po \
   php/*.php \
   lib/*.plib
