#!/bin/sh

# AIRT: APPLICATION FOR INCIDENT RESPONSE TEAMS
# Copyright (C) 2005   Tilburg University, The Netherlands

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# wrapper_none -- wrapper for the default, inert wrapper task.
# See airt_export(1) for more details.
# 
# $Id$

# Typically, wrappers are fully silent when everything goes right, but this
# makes a bad demo.
echo "This is wrapper_none."
taskid=$1
if [ "$taskid" = "" ]; then
  echo "ERROR: Task ID must be provided as first parameter."
  exit 1
fi
echo "We run as export queue task $taskid."
shift
echo "Parameters: $1, $2, $3."
echo "Sleeping five seconds..."
sleep 5
echo "Waking up. Sending result to export queue..."
airt_export --result-id=$taskid --result-code=OK --result-msg="Hello, world."
if [ $? != 0 ]; then
  echo "Bailing out."
  exit 1
fi
echo "wrapper_none done."
